### ISSUE TITLE
Téléchargement | Droits d'auteur

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#108]
**Description de l'évolution**
Actuellement toutes les photos sont téléchargeables avec un message les mettant en licence ouverte 2.0. 
Sont en licence ouverte 2.0 les photos d'Isabelle Bideau et Murielle Cinqpeyre concernant les prises d'objets produits avant 1900 (année de création) et avant 20e siècle (époque de création).

Pour les autres, elles sont téléchargeables mais réservées à un usage personnel. Il est donc nécessaire d'intégrer cet autre message pour ces images :
<img width="1152" alt="info telechargement 3" src="https://user-images.githubusercontent.com/36261410/51259662-e2b39500-19ac-11e9-8daa-680b9ab10620.png">

**Comment by nedbaldessin** [comment]
Petite précision: j'ai mis la limite de Licence Ouverte à l'année courante moins 70 ans (qui correspond au passage dans le domaine public).
