### ISSUE TITLE
Recherche de plusieurs mots

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#121]
**Description du défaut**
À la recherche libre de "bureau à cylindre" ceux-ci ne sortent pas dans les résultats.

**Comportement attendu**
Trouver sur les bureaux à cylindre
> booster les titre/appellation et dénomination
> recherche sur plusieurs mots à améliorer

**Comment by lauriechap** [comment]
Je pense que le scoring de "type d'objet" est vraiment trop haut. Par exemple ci dessous quand on cherche un objet qui n'est pas renseigner dans les types d'objets, les résultats ne sont pas pertinents.
<img width="1412" alt="capture d ecran 2019-02-04 a 11 58 00" src="https://user-images.githubusercontent.com/36261410/52204433-6823ba00-2874-11e9-87db-a525c02cccd9.png">
<img width="1411" alt="capture d ecran 2019-02-04 a 11 57 44" src="https://user-images.githubusercontent.com/36261410/52204437-6a861400-2874-11e9-95ba-9120ee93d110.png">

**Comment by nedbaldessin** [comment]
Corrigé. Les types ont un boost de 3, comme les noms d'auteurs.
