### ISSUE TITLE
crédit photo © Mobilier National

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#122]
**Description de la modification à éffectuer**
Au téléchargement d'une photographie : ajouter le crédit © Mobilier National dans le nom du fichier téléchargé.

**Comment by Lully** [comment]
Autre problème : il n'y a qu'un crédit qui apparaît, celui de la photo principale. Quand on clique sur une autre photo, on n'a pas le crédit photographique lui correspondant. C'est un problème important. 3.2.2019

**Comment by lauriechap** [comment]
Ok, je vais créer un nouveau ticket car il ne s'agit pas exactement du même problème. Merci

**Comment by nedbaldessin** [comment]
Fait.
