### ISSUE TITLE
Sélection type d'objet

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#133]
**Description du défaut**
Si l'on sélectionne une sous catégorie d'objet (Art graphique>**dessin**), Art graphique est sélectionné. Il faudrait garder seulement dessin comme dans la version précédente de l'interface. Cf capture 
<img width="851" alt="capture d ecran 2019-02-18 a 16 47 25" src="https://user-images.githubusercontent.com/36261410/52963652-ab1b7c80-33a0-11e9-9f01-22dd979a2b61.png">
<img width="884" alt="capture d ecran 2019-02-18 a 17 12 42" src="https://user-images.githubusercontent.com/36261410/52963653-ab1b7c80-33a0-11e9-9f31-2da85e83a388.png">

**Comment by nedbaldessin** [comment]
Fixé.
@lauriechap pour info, j'avais fait cela pour refléter le design visible dans #70 ou Figma > Corrections UX > hover/select

**Comment by lauriechap** [comment]
@nedbaldessin désolée :/
