### ISSUE TITLE
sous catégorie type objet

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#14]
**Description du défaut**
Lors du clic sous une sous catégorie d'objet exemple " armoire", la catégorie mère "rangement" apparait elle aussi dans le critères de recherches. On voit donc tous les rangements alors que l'objectif était de voir seulement les armoires.

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'type d'objet'
3. Faire défiler la page jusqu'à 'rangement'
2. Cliquer sur 'armoire'
4. Voir l'erreur

**Comportement attendu**
Au clic sur armoire, seulement les armoires apparaissent, dans les résultats comme dans la phrase de critères.

**Comment by lauriechap** [comment]
il sera toujours possible de sélectionner "rangement", mais si sélection d'une sous catégorie comme "armoire", ne laisser que ce dernier.

**Comment by nedbaldessin** [comment]
L'UX des filtres hierarchiques a été revu et corrigé dans la branche "ux-change-types".
