### ISSUE TITLE
hover type d'objet

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#145]
**Description du défaut**
Le hover du panneau deux est beaucoup trop blanc. Adaptez suivant les maquettes
<img width="862" alt="capture d ecran 2019-03-06 a 11 20 20" src="https://user-images.githubusercontent.com/36261410/53874086-033dba00-4002-11e9-951a-9ef2f12fef82.png">

**Comment by nedbaldessin** [comment]
Fixé.
