### ISSUE TITLE
Recherche libre

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#147]
**Description du défaut**
Actuellement la recherche de plusieurs mots ne fonctionne pas.
Exemple ci-dessous :
<img width="1564" alt="capture d ecran 2019-03-08 a 14 25 12" src="https://user-images.githubusercontent.com/36261410/54031351-cbc04080-41ae-11e9-9d27-8081abfc8b65.png">
<img width="1557" alt="capture d ecran 2019-03-08 a 14 25 54" src="https://user-images.githubusercontent.com/36261410/54031360-d084f480-41ae-11e9-8af9-b8126d030bdf.png">
<img width="1563" alt="capture d ecran 2019-03-08 a 14 29 07" src="https://user-images.githubusercontent.com/36261410/54031373-d8dd2f80-41ae-11e9-80a4-f89adb5ebb26.png">

Ci dessous un exemple de recherche "table empire" en champ libre puis par les filtres :
<img width="1563" alt="capture d ecran 2019-03-08 a 14 27 37" src="https://user-images.githubusercontent.com/36261410/54031385-df6ba700-41ae-11e9-8bd2-e5f01a9390f6.png">
<img width="1567" alt="capture d ecran 2019-03-08 a 14 28 01" src="https://user-images.githubusercontent.com/36261410/54031400-eb576900-41ae-11e9-9fcf-b10070b79212.png">
Les resultats avec ces deux process de recherche devrait se rapprocher fortement.

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Rechercher "table empire" dans la recherche libre
2. Voir l'erreur

**>>> après discussion : afficher seulement les résultats qui ont tous les mots dans leur fiche.**

Autre problème que cette solution devrait régler : 
<img width="1607" alt="Capture d’écran 2019-03-12 à 12 04 00" src="https://user-images.githubusercontent.com/36261410/54195450-f831d080-44be-11e9-9ba0-b1e38467f09f.png">

**Comment by nedbaldessin** [comment]
Corrigé avec  [40b7299]
