### ISSUE TITLE
champ acquisition

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#153]
**Défault**
Il y a trois champs dans SCOM pour champ origine du bien (date, mode d'acquisition, détail d'acquisition), pour le moment c'est le détail d'acquisition qui sort.

**Résultats souhaités**
 il faut mettre uniquement date + mode d'acquisition.

**Comment by nedbaldessin** [comment]
Changed in [a7c6dd35dd1f995e7431308d33e221d77e1204e9] and [3f3650dc4ad7e05f6aaf2a7f3aa48b0f9dc627a6]
