### ISSUE TITLE
Rediriger le sous-domaine WWW sur l'URL de production

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#155]

**Comment by nedbaldessin** [comment]
Je reprécise : on devrait rediriger les requêtes pour :
`https://www.collection.mobiliernational.culture.gouv.fr`
vers
`https://collection.mobiliernational.culture.gouv.fr`
…qui est le domaine de production.

**Comment by nedbaldessin** [comment]
Après discussion avec la SDSI : mettons en place la redirection lorsque nous aurons repris possession du domaine en `.fr`, parce qu'actuellement cela voudrait dire acheter de nouveaux certificats SSL.
Je passe en icebox.

**Comment by lauriechap** [comment]
👍
