### ISSUE TITLE
enlever "null" pour les auteurs sans prénom

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#159]
<img width="261" alt="Capture d’écran 2019-03-19 à 18 35 50" src="https://user-images.githubusercontent.com/36261410/54628482-ef6c6c00-4a75-11e9-8bf5-31b9ddb31166.png">

visible sur les critères de recherche

**Comment by nedbaldessin** [comment]
Corrigé dans [1012241]
