### ISSUE TITLE
Concevoir une image d'illustration du repo GitHub

### ISSUE THREAD

**Issue by nedbaldessin** [entrepreneur-interet-general/gobelins#171]
Nouveauté GitHub : maintenant, quand on partage l'URL d'un repo sur les réseaux sociaux, on peut spécifier l'image d'illustration à utiliser (champ OpenGraph Image). Sinon, par défaut, c'est le portrait du dernier contributeur, en GROS.

Donc voilà, c'est juste un truc à faire si ça t'amuses.

Suggestion de contenu : 
"Moteur de la collection du Mobilier national"
<logo MN> <logo MCC> …
fond patchwork d'images colorées, ponpons, etc

Il faut que l'image fasse 1280×640px, au format PNG ou JPG.
![Gabarit proposé par GitHub](https://user-images.githubusercontent.com/69353/56366938-7edf7900-61f4-11e9-81fb-e49d98e92c0b.png)

**Comment by lauriechap** [comment]
@nedbaldessin 
![github_mn](https://user-images.githubusercontent.com/36261410/56372406-32e60180-61ff-11e9-8517-bf2ba57fbff5.jpg) c'est cadeau avec pompom et tout ce qui faut !

**Comment by nedbaldessin** [comment]
Cool merci :)
