### ISSUE TITLE
filtrer / rechercher sur mobile

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#175]
après avoir filtrer sur mobile, l'icone recherche se retrouve sélectionné = enlever le select.
![IMG_2975](https://user-images.githubusercontent.com/36261410/58164260-c343b600-7c85-11e9-9842-3b67aa678d9b.PNG)

**Comment by nedbaldessin** [comment]
@lauriechap Je ne parviens pas à reproduire ce bug. Testé sur Safari, Firefox, et Chrome, sous iOS. On s'en parle ?

**Comment by lauriechap** [comment]
@nedbaldessin je viens de vérifier / plus de bug :)
