### ISSUE TITLE
Recherche multiple

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#179]
à la recherche de "nicolas" en champ libre puis de "tapisserie" via type d'objet, une page blanche apparait.

D'après les tests cela se reproduit à chaque fois qu'il y a un croisement de recherche entre type d'objet et recherche libre.

**Comment by nedbaldessin** [comment]
Corrigé sur [44b87c7def93befd7ef2d6c4058c2a48d521c2db]
Visible sur beta/staging.
