### ISSUE TITLE
ordre auteur

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#180]
classer par Nom de famille, prénom les auteurs.
La liste semble avoir bouger depuis le dernier déploiement, et complexifie la recherche par auteur.
<img width="363" alt="Capture d’écran 2019-05-29 à 11 12 37" src="https://user-images.githubusercontent.com/36261410/58545145-f85e8400-8202-11e9-9740-ae56c28fb3ed.png">

**Comment by nedbaldessin** [comment]
Corrigé avec [c094afb]
