### ISSUE TITLE
corriger mise en forme overlay, plus résultats.

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#185]
Voir photo ci-jointe
![IMG_4923](https://user-images.githubusercontent.com/36261410/59494534-9f8f1c80-8e8d-11e9-9c35-02a97e695509.JPG)

**Comment by nedbaldessin** [comment]
@lauriechap Te souviens-tu de la recherche effectuée ? J'ai l'impression que le problème est différent du ticket #195 parce que les cartouches blancs avec le nombre de résultats ont l'air différents. Toute info bienvenue.

**Comment by nedbaldessin** [comment]
Malgré mes tests, je ne parviens toujours pas à reproduire ce bug. Merci de ré-ouvrir le bug si jamais on le constatait à nouveau.
