### ISSUE TITLE
sur ipad pro / le filtre dimension ne fonctionne pas

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#187]
En essayant de changer les dimensions, le scroll horizontal fait bouger les panneaux entièremment, pas seulement les curseurs hauteur, largeur, longueur
![IMG_5051](https://user-images.githubusercontent.com/36261410/59494892-728f3980-8e8e-11e9-9215-3053f5d8cbe0.JPG)

**Comment by nedbaldessin** [comment]
Je ne parviens pas à reproduire le bug.
@lauriechap si tu as plus d'infos, ou si tu parviens à reproduire, ça m'intéresse.
