### ISSUE TITLE
sur ipad pro / le titre de la fiche objet ne se place pas correctement

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#188]
Voir image (désolée pour la qualité des images / prises à la volée durant les présentations)

![IMG_6748](https://user-images.githubusercontent.com/36261410/59495267-46c08380-8e8f-11e9-823c-be3ac3f28514.JPG)

![IMG_5299](https://user-images.githubusercontent.com/36261410/59495287-53dd7280-8e8f-11e9-8c84-c9f1095cf9cd.JPG)

![IMG_6748](https://user-images.githubusercontent.com/36261410/59495371-6f487d80-8e8f-11e9-9a3c-2b75dfce4d89.JPG)

**Comment by nedbaldessin** [comment]
Je ne parviens pas à reproduire le bug. Vraisemblablement déjà corrigé.
