### ISSUE TITLE
recherche libre - nouvelle recherche

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#19]
**Description du défaut**
après une recherche celle-ci reste inscrite dans la recherche libre, il est nécessaire de l'effacer manuellement

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'rechercher'
3. Taper la recherche 
4. Voir l'erreur

**Comportement attendu**
Une fois la recherche inscrite dans la phrase, revenir à la phrase de base "rechercher dans les collections du MN"

**Comment by nedbaldessin** [comment]
@lauriechap je n'arrive pas à reproduire ce problème. Pour moi le champ texte se remet bien à zéro quand tu lances la requête (touche entrée ou bouton loupe).

**Comment by lauriechap** [comment]
@nedbaldessin après vérification cela se produit au retour d'une fiche objet

**Comment by nedbaldessin** [comment]
Fixed in d86f47e
