### ISSUE TITLE
Corriger mise en forme téléchargement mobile + tablette

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#192]
![image verticale](https://user-images.githubusercontent.com/36261410/59841346-6c003680-9354-11e9-920e-30aa3e4d9a50.png)
Actuellement :
![IMG_3850](https://user-images.githubusercontent.com/36261410/59840699-2d1db100-9353-11e9-957c-a0fa773071e5.jpg)

Correction :
<img width="320" alt="iPhone SE" src="https://user-images.githubusercontent.com/36261410/59841331-6571bf00-9354-11e9-8494-da70b152c907.png">

**Comment by nedbaldessin** [comment]
Corrigé en [2217889]
