### ISSUE TITLE
corriger apparition de 2 loaders, 2 "résultats"

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#195]
<img width="2322" alt="Capture d’écran 2019-07-22 à 10 02 04" src="https://user-images.githubusercontent.com/36261410/61616102-e7ad1600-ac67-11e9-8ac1-8cd2751f1672.png">

lié à ticket #185

**Comment by nedbaldessin** [comment]
Corrigé.
