### ISSUE TITLE
Attente de 3, 4min pour pouvoir faire une recherche libre

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#196]
sur PC / version firefox ministère de la culture la recherche libre est bloquée pendant 3/4 minutes avant de pouvoir cliquer et réaliser cette recherche.
Plusieurs agents ont fait remonter ce bug.

Voir issue #22

**Comment by nedbaldessin** [comment]
Je ne parviens ni à constater, ni à reproduire ce problème. Testé sur plusieurs postes (anciens) du ministère, sous Firefox.
