### ISSUE TITLE
Zoom long à ouvrir (45sec) par exemple pour le GMMP 9

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#198]

**Comment by nedbaldessin** [comment]
L'image zoomée du [GMMP 9](https://collection.mobiliernational.culture.gouv.fr/objet/GMMP-9-000/zoom) fait environ **5.5 Mo**. Donc c'est normal que ce soit un peu lent. Mais sur un connexion haut débit, ça ne devrait pas prendre plus que 10-15 secondes.

45 secondes c'est vraiment étonnant, et cela doit être en raison d'une fluctuation de bande passante.

La solution pour ce problème, c'est de gérer les images sous forme de piles de tuiles (comme Google Maps ou autre). C'est un chantier important, qu'on peut inscrire dans la roadmap, mais qui ne me paraît pas urgent pour le moment.
