### ISSUE TITLE
Une fois une dimension renseignée, l'interface ne prend plus en compte de nouvelles dimensions. Il est nécessaire de supprimer le critère et recommencer à 0.

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#199]
<img width="1445" alt="Capture d’écran 2019-09-04 à 15 31 05" src="https://user-images.githubusercontent.com/36261410/64260565-6239a880-cf2b-11e9-89ec-e4df1687be65.png">

**Comment by nedbaldessin** [comment]
Reformulation:
Après avoir effectué une recherche avec des dimensions, si on remet les sliders en position minimale/maximale, le nombre de résultats ne change pas. Dans la screenshot, on a toujours 5 résultats, alors qu'il devrait en avoir 1252.

Peut-être supprimer le critère dimension une vois qu'on a remis le slider en bout de rail ?
