### ISSUE TITLE
recherche libre - numéro d'inventaire

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#20]
**Description du défaut**
la recherche libre ne permet pas la recherche efficace des numéros d'inventaires.

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'rechercher
3. Inscrire un numéro d'inventaire
4. Voir l'erreur

**Comportement attendu**
à la recherche d'un numéro d'inventaire, les objets répertoriés avec son numéro sortent en premier

**Comment by nedbaldessin** [comment]
Maintenant, l'objet avec le numéro d'inventaire sort bien en premier.
Mais je pense qu'on peut améliorer: on a toute une floppée d'autres objets, ce qui n'est pas très intuitif… Peut-être on pourrait reconnaître les recherches ayant la forme d'un numéro d'inventaire (c'est à dire `[lettres]-[chiffres ou lettres]-[3 chiffres]`), et faire une recherche spécifique ? Ou alors ajouter un mode de saisie pour les numéros d'inventaire ?
À creuser, plus tard.
@lauriechap je te laisse décider si ce ticket est résolu ou non.

**Comment by lauriechap** [comment]
👍 Je suis d'accord pour que l'on reconnaisse une recherche de numéro d'inventaire si c'est possible, ce serait bien plus pertinent ! dans les tests j'ai vu que les utilisateurs écrivent différemment (avec ou sans tiret) ce qui complexifie la détection. 
On a ici la liste des premières lettres d'immatriculation : http://www.mobiliernational.culture.gouv.fr/fr/collections-et-ressources/marques-dinventaire à partir du moment ou celles-ci sont suivies de (espace ou tiret + nombre) ou (nombre) il s'agit d'une recherche de numéro d'inventaire. Est-ce possible ? Et sinon ; oui on ajoutera un champ de recherche inventaire plus tard. @nedbaldessin

**Comment by nedbaldessin** [comment]
Pour l'emploi de tirets ou d'espace, c'est transparent pour la recherche (ils sont retirés).

Je pense qu'il faut spécifier mieux le comportement voulu. Par exemple: si on a un match parfait avec un numéro d'inventaire (préfixe+numéro+série), alors on l'affiche d'une façon différenciée (encadré, étiquette…). Si on matche sur un préfixe seulement, peut-être qu'on veut afficher ça autrement…
Bref, on peut y réfléchir, mais c'est tout un usage. Et je me demande si ce n'est pas avant tout un usage interne, qui sera pourvu par Flora.
Donc je ferme le ticket. Libre à toi d'en recréer qui spécifie le nouveau comportement :)
