### ISSUE TITLE
Arrondir les dimensions avec des crans de 0,25

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#206]
pour parvenir plus facilement à inscrire la dimension que l'on souhaite
<img width="232" alt="Capture d’écran 2019-09-13 à 14 06 31" src="https://user-images.githubusercontent.com/36261410/64861379-1922dc00-d630-11e9-99bf-73e467046702.png">

**Comment by nedbaldessin** [comment]
Bon, c'est fait, mais pense que c'est une fausse bonne idée :)

Pour les *longueurs* c'est pas mal, mais pour les autres deux dimensions (dont l'intervale est plus réduit) deviennent moins précis (on est forcément moins proche de la dimension que l'on souhaite).

À mon avis, il faudrait que les valeurs numériques soient des champs texte, pour qu'on puisse effectuer une saisie au clavier précise en cas de besoin.
