### ISSUE TITLE
Au téléchargement sur mobile, il est impossible de lire le message de téléchargement, celui-ci apparait que quelques instants.

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#209]
Est-ce possible d'empêcher l'ouverture instantanée de l'image pour permettre la lecture ?

**Comment by nedbaldessin** [comment]
@lauriechap  Je vois. Le problème, c'est que c'est le comportement normal d'iOS : comme il n'y a pas d'équivalent au dossier "Téléchargements", l'image n'est pas enregistrée localement, et Safari affiche l'image. On peut alors sauvegarder l'image (sur iCloud, Dropbox, etc), la partager, etc. Le bouton [back] fonctionne pour revenir à la modale de téléchargement.

Une solution serait de ne pas lancer le téléchargement à l'ouverture de la modale, mais avoir sur celle-ci un bouton [Télécharger]. Dans la modale, on voit les modalités de licence, etc, et on décide ou non de télécharger.

Parlons-en !

**Comment by lauriechap** [comment]
@nedbaldessin 
voici :)
![image verticale](https://user-images.githubusercontent.com/36261410/64942457-6473ff00-d869-11e9-818e-e27212af6a59.png)
<img width="320" alt="iPhone SE (9)" src="https://user-images.githubusercontent.com/36261410/64942459-6473ff00-d869-11e9-882e-429f37220bfa.png">

**Comment by nedbaldessin** [comment]
Fait.

**Comment by nedbaldessin** [comment]
Le problème initial est spécifique à iOS version 12 et inférieur. Il a été résolu en version 13. Le problème n'existe pas sous Android (testé dans Browser et Chrome), qui affiche un dialogue de confirmation de téléchargement.

Par conséquent, je suis revenu au comportement initial, en faisant l'impasse sur les iOS anciens.
