### ISSUE TITLE
Type d'objets vides 

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#21]
**Description du défaut**
au clic dans la sous-catégorie "banc" dans type d'objet, il n'y a aucun resultat

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'type d'objet'
3. Cliquer sur 'banquette et tabouret'
4. Cliquer sur 'banc'
5. Voir l'erreur

**Comportement attendu**
Au clic sur banc, différents bancs apparaissent dans les résultats de recherche.

**Comment by lauriechap** [comment]
absence de contenu aussi pour "bergère"
<img width="1720" alt="capture d ecran 2018-11-27 a 14 18 29" src="https://user-images.githubusercontent.com/36261410/49085145-9de36b80-f251-11e8-95e1-119a997e7724.png">

**Comment by nedbaldessin** [comment]
Fix à valider lors du prochain import de données.

**Comment by nedbaldessin** [comment]
OK pour `banc`.
Pour `bergère`, le mapping les classait dans `Fauteuil`, donc j'ai corrigé mais ce sera visible au prochain re-import.
