### ISSUE TITLE
Temps de chargement zoom

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#212]
Malgré notre discussion, j'ai l'impression que le temps de chargement pour le zoom n'est plus aussi bon qu'avant. 
ex : teléchargement sur ipad de cette image http://beta.collections-mobilier-national.com/objet/GMT-33191-000

résultat :
![IMG_0714](https://user-images.githubusercontent.com/36261410/64864043-7f126200-d636-11e9-881c-8b10b99c9357.PNG)
après 15 sec avec le loader.

**Comment by nedbaldessin** [comment]
@lauriechap Alors je pense que ce n'est pas un pas un problème de lenteur, mais que le navigateur plante par manque de mémoire lorsque le zoom manipule une grosse image (plus de 7 Mo pour celle-ci). Pourrais-tu amener au bureau l'appareil qui a servi pour ce test ? Sur les appareils que j'ai je n'arrive pas à le reproduire. Merci !

**Comment by lauriechap** [comment]
@nedbaldessin Cela se produit aussi sur mon ordinateur du bureau. On peut regarder cela sur celui-ci.

**Comment by nedbaldessin** [comment]
Donc après analyse, j'ai créé un nouveau ticket pour cette amélioration : #219
