### ISSUE TITLE
Mobile et tablette > titre du filtre "Styles" enlever le "s" et mettre à la même taille que les autres

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#217]
![IMG_0709](https://user-images.githubusercontent.com/36261410/64864794-2774f600-d638-11e9-89a9-b6a4d38d54b8.PNG)

**Comment by nedbaldessin** [comment]
@lauriechap Coucou je ne comprends pas ce que tu veux dire par "mettre à la même taille que les autres". La typo est à la même taille que les autres panneaux. La taille du panneau aussi. 🤔
