### ISSUE TITLE
réactivité recherche

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#22]
**Description du défaut**
lors d'une recherche depuis les ordis du MN il est est nécessaire d'attendre entre 0.5 et 3 secondes pour voir le critère de recherche apparaî

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'fauteuils'
3. Voir l'erreur

**Comment by nedbaldessin** [comment]
Je ne parviens ni à constater, ni à reproduire ce problème. Testé sur plusieurs postes (anciens) du ministère, sous Firefox.
