### ISSUE TITLE
Prise en compte des accents dans la recherche libre

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#220]
- À la recherche de "noel" ou "noël" on ne trouve pas les mêmes résultats 

- À la recherche de "venus" ou "vénus" même problème 
>enlever la prise en compte des accents

- À la recherche de "notre dame" il n'y a pas de résultats, alors qu'avec "notre-dame" nous trouvons les résultas / seulement ceux-ci n'arrivent pas en premier
> ignorer les traits d'unions ?
> identifier le problème de ces résultats / j'ignore pourquoi ces résultats tombent dans cette ordre.

**Comment by nedbaldessin** [comment]
Fixé.
Je mets de côté pour l'instant le cas "Notre-dame", le trait d'union pose un problème pour lequel il faudrait prendre un temps plus long d'investigation (c.f: https://github.com/elastic/elasticsearch/issues/29148#issuecomment-376458216 ).
