### ISSUE TITLE
Enlever s'identifier + pas encore inscrit ? dans les captures ci-dessous

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#225]
<img width="2469" alt="Capture d’écran 2019-10-16 à 15 50 44" src="https://user-images.githubusercontent.com/36261410/66926150-c9b83d00-f02d-11e9-8705-be164fa1fc11.png">
<img width="812" alt="Capture d’écran 2019-10-16 à 15 46 42" src="https://user-images.githubusercontent.com/36261410/66926266-01bf8000-f02e-11e9-9501-c292051608df.png">

<img width="735" alt="Capture d’écran 2019-12-02 à 14 29 42" src="https://user-images.githubusercontent.com/36261410/70035696-ab91a680-15b3-11ea-9cdd-78c136986b69.png">

<img width="737" alt="Capture d’écran 2019-12-02 à 15 09 33" src="https://user-images.githubusercontent.com/36261410/70035983-2bb80c00-15b4-11ea-84a2-62cd4c7ed0b6.png">

<img width="739" alt="Capture d’écran 2019-12-02 à 14 34 21" src="https://user-images.githubusercontent.com/36261410/70130445-dbf34680-1680-11ea-95e0-96fb0b6a433b.png">

**Comment by nedbaldessin** [comment]
Pour mémoire : après discussion et désaccord sur l'UX, nous avons évoqué de conserver ces liens de navigation croisée, mais avec un style d'affichage différent, pour mieux les identifier comme de la nav.
En attendant, j'ai répondu à la demande et supprimé les liens de nav.
