### ISSUE TITLE
Au clic sur participer à une collection > l'utilisateur n'atterit pas sur la sélection en question

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#226]
à la réception du mail nous invitant à collaborer à une collection, l'utilisateur clic sur "participer" et n'atteint pas la sélection en question mais la page des objets aléatoires

**Comment by nedbaldessin** [comment]
J'ai retesté ce flow, et cela fonctionne.
A priori, si tu a cliqué sur le lien dans l'email, et tu as atterri sur les objets aléatoires, c'est que le navigateur était encore identifié. Il faut utiliser un autre navigateur, une fenêtre incognito, etc.
Tu confirmes ?

**Comment by lauriechap** [comment]
yes 👍 👍 👍
