### ISSUE TITLE
Intégrer balise nom plutôt que mail sur l'invitation à participer

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#229]
code ici : https://codepen.io/lauriechap/pen/eaymxz

développé actuellement :
<img width="585" alt="Capture d’écran 2019-10-16 à 17 49 45" src="https://user-images.githubusercontent.com/36261410/66936149-836ada00-f03d-11e9-84b7-d813d01812c3.png">

**Comment by nedbaldessin** [comment]
Le formulaire d'invitation identifie les invités par une adresse email (et uniquement cela).

Pour les utilisateurs référencés, nous utilisons le nom dans l'email d'invitation, puisque nous l'avons.
Pour les adresses email qui ne correspondent à aucun utilisateur du système, on ne peut pas utiliser le nom, puisqu'on ne le connait pas.

Si tu veux changer ce comportement, il faut modifier le formulaire d'invitation pour utiliser deux champs : nom et adresse email.
