### ISSUE TITLE
Confirmation de son adresse mail impossible

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#231]
page apparaissant au clic sur confirmer :
<img width="367" alt="Capture d’écran 2019-10-16 à 17 55 17" src="https://user-images.githubusercontent.com/36261410/66936551-33404780-f03e-11e9-8933-a14fd62e32dd.png">

**Comment by nedbaldessin** [comment]
@lauriechap Pour moi le flow de confirmation des emails suite à l'enregistrement d'un nouvel utilisateur fonctionne bien. Pourrais-tu me préciser les étapes de ce bug si tu parviens à le reproduire ? Merci.
