### ISSUE TITLE
Connexion - perte d'un mot de passe - comment fait-on pour en avoir un nouveau ?

### ISSUE THREAD

**Issue by Lully** [entrepreneur-interet-general/gobelins#234]
**Processus pour le constater**
1. Aller sur la page 'http://beta.collections-mobilier-national.com/recherche'
2. Cliquer sur 'un cœur de sorte d'entrer qu'on vous demande de vous connecter.'
3. Voir l'erreur - si j'ai perdu mon mot de passe je reste coincé.

**Comportement attendu**
J'aurais dû recevoir un courriel avec code par courriel et j'aimerais aussi pouvoir changer mon mot de passe sur mon espace perso (que j'ai désormais du mal à trouver en bas à droite ou à gauche comme sur d'autres sites).

**Comment by nedbaldessin** [comment]
Les comportements de réinitialisation du mot de passe, et de perte de mot de passe, ont été déployés vendredi.
Vous devriez recevoir correctement les emails lors de l'oubli du mot de passe.
Pour le changement du mot de passe quand on est identifié, cela se faire sur la fenêtre modale d'édition des informations personnelles.
