### ISSUE TITLE
recherche libre - type d'objet

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#24]
**Description du défaut**
À la recherche libre "tapisserie" les premiers résultats ne sont pas des tapisseries

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'rechercher'
3. Écrire 'tapisserie'
4. Voir l'erreur

**Comportement attendu**
les tapisseries tombent dans les premiers résultats

**Comment by lauriechap** [comment]
@nedbaldessin après re-indexation ce n'est pas optimal. Par exemple pour "modèle de tapisserie", "chaise", "bois rose"… Ne faut il pas faire que les infos "type, auteur, matière" soient prioritaires sur le titre ?

**Comment by lauriechap** [comment]
<img width="1582" alt="capture d ecran 2018-11-30 a 10 44 33" src="https://user-images.githubusercontent.com/36261410/49281509-0c603d80-f48d-11e8-9a07-275a8637ad6a.png">

**Comment by nedbaldessin** [comment]
Résolu avec  a41cc48.

J'ai grandement augmenté le boost pour les types, auteurs, et matières.
