### ISSUE TITLE
Image en aperçu des sélections

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#244]
@nedbaldessin Le système des 4 images donnant l'aperçu de la sélection à changer. Pourrais tu m'expliquer le nouveau système mis en place, je n'arrive pas à comprendre la logique. 
merci

**Comment by nedbaldessin** [comment]
Cela se joue ici:
https://github.com/entrepreneur-interet-general/gobelins/blob/5c4cbdc582939dfbc21c61bfd9132d53aecea643/app/Models/Selection.php#L55

On liste les 4 (ou moins) objets, par ordre de qualité d'image. Ce score de qualité est établi selon les règles suivantes:
- si l'image a été classifiée "de qualité" par Hélène, et que le photographe est I. Bideau => 5
- si l'image a été classifiée "de qualité" par Hélène, mais que le photographe est autre => 3
- sinon => 2
- et enfin, si on n'a pas d'image du tout => 0

À noter: actuellement l'image principale n'est pas forcément celle de SCOM, ce point est encore en cours.

**Comment by lauriechap** [comment]
Ok, je me permets de laisser le ticket ouvert car je trouve ça pas explicite pour l'internaute et le résultat n'est pas optimal, je ne sais pas ce que tu en penses. On en parle de vive voix ? Mais ce n'est pas une priorité.
