### ISSUE TITLE
recherche libre - auteur

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#25]
**Description du défaut**
À la recherche d'un artiste dans le recherche libre, tous les résultats ne sortent pas

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'rechercher'
3. Écrire  'Paulin'
4. Voir l'erreur

**Comportement attendu**
L'ensemble des objets réalisés par Paulin devrait sortir

**Comment by lauriechap** [comment]
@nedbaldessin à la recherche de certains auteurs comme "Picasso" on se retrouve avec du "Giacometti" je n'arrive pas à identifier pourquoi il apparait dans cette recherche.

**Comment by nedbaldessin** [comment]
@lauriechap En effet, les lustres de Giacometti font partie d'une acquisition pour le **musée Picasso**, ce qui n'était, jusqu'à présent, pas affiché.
