### ISSUE TITLE
Ajouter la croix en permanence sur les objets dans les sélections pour pouvoir les supprimer

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#251]
maquettes 
<img width="320" alt="sélection" src="https://user-images.githubusercontent.com/36261410/67701505-56f57d00-f9b0-11e9-98a8-828a9fcd41ca.png">

capture
<img width="436" alt="Capture d’écran 2019-10-28 à 18 21 29" src="https://user-images.githubusercontent.com/36261410/67701521-61177b80-f9b0-11e9-83c6-12d9a80d11ec.png">

**Comment by nedbaldessin** [comment]
@lauriechap La screenshot que tu montres est sur fond blanc, ce qui indique que **l'utilisateur courant n'est pas collaborateur** pour la sélection affichée. Et dans ce cas, on ne veut pas afficher la bouton suppression, right ?

**Comment by lauriechap** [comment]
@nedbaldessin yes, je me suis trompée. Tu as entièrement raison :)
