### ISSUE TITLE
Aperçu des sélections, remettre les premiers objets ajoutés en aperçu

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#257]
En attendant de permettre la customisation précise des aperçus par les utilisateurs, mettre les 4 premiers objets. Cela permets de pouvoir gérer tout de même les apercus si on le souhaite. 
Le résultat avec l'algo n'étant pas optimal pour l'instant. 

Pour l'instant l'image à la une de SCOM n'est pas forcément celle en aperçu dans les sélections cf : http://beta.collections-mobilier-national.com/objet/GMTC-482-002

**Comment by nedbaldessin** [comment]
Fait.
