### ISSUE TITLE
Centrer texte / cartouche

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#263]
<img width="250" alt="Capture d’écran 2019-12-02 à 14 41 32" src="https://user-images.githubusercontent.com/36261410/69964172-273b1700-1512-11ea-9f5e-db0af24e0394.png">

**Comment by nedbaldessin** [comment]
Coucou @lauriechap je comprends pas quel alignement tu voudrais.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/69353/72062769-b806ce80-32d8-11ea-8536-bf36b2839263.png">

**Comment by lauriechap** [comment]
@nedbaldessin Hey ! Sorry pour le manque de précision, il s'agit d'une correction optique, bottom : 28px / top : 26px
thanks
