### ISSUE TITLE
Invitation collaborateur

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#264]
Une fois email renseigner, la touche entrée permet d'envoyer l'invitation

Au clic sur enregistrer, si le champ inviter un collaborateur est remplit > envoyer l'invitation

Lors des tests, les utilisateurs cliquaient sur enregistrer  pour envoyer

**Comment by nedbaldessin** [comment]
Nouveau comportement pour résoudre le problème d'UX sans toucher à trop de choses : quand l'utilisateur saisi dans le champ email d'invitation, un overlay couvre le reste du formulaire, afin de rendre plus évident qu'on est entré dans un mode de saisie (la touche entrée envoie l'invitation, mais ne valide pas le formulaire entier).
