### ISSUE TITLE
Ajouter padding-top 5px > AuthModal_switch_links

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#274]
<img width="737" alt="Capture d’écran 2019-12-02 à 15 09 33" src="https://user-images.githubusercontent.com/36261410/70036333-ddefd380-15b4-11ea-93e4-de3b3b50b53c.png">

Au dessus des infos telles que " Mot de passe oublié ?" ajouter padding top 5 px

**Comment by nedbaldessin** [comment]
Dans le ticket #225 nous supprimons ces liens de navigation (fait : 25bfb0d), ce ticket est donc obsolète.
