### ISSUE TITLE
Conserver état de page voir plus

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#275]
Après plusieurs clic sur voir plus > puis clic sur une des sélections > puis retour = on arrive sur les 4 premières sélections. L'ensemble des sélections déroulées n'est plus visible, on doit de nouveau cliquer plusieurs fois sur voir plus.
Serait-il possible de revenir à l'endroit du déroulé des sélections ?

**Comment by nedbaldessin** [comment]
Comme discuté au téléphone, sur la page de listing des sélections, les items chargés via les boutons [Voir Plus] sont conservés quand on revient sur la page.

En revanche, la conservation d'un état de scroll induit un changement de comportement du bouton [flèche gauche] vers celui du bouton [Back] du navigateur, ce qui n'est pas le cas aujourd'hui, et qui mérite d'être réfléchi avec la nouvelle site map (savoir-faires, etc).
