### ISSUE TITLE
Sélection du MN non visible avec connexion

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#278]
En étant connecté avec le compte MN, au clic sur "explorer les sélections" j'arrive une fois sur deux sur la page me proposant de créer ma première sélection. Impossible d'accéder aux anciennes

<img width="2415" alt="Capture d’écran 2019-12-03 à 11 35 18" src="https://user-images.githubusercontent.com/36261410/70043723-45138500-15c1-11ea-8d54-b4269a1b06d8.png">

**Comment by nedbaldessin** [comment]
@lauriechap Je ne parviens pas à reproduire ce bug, je pense qu'il a été résolu dans un changement de la semaine dernière.
