### ISSUE TITLE
filtre auteur / alphabet

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#287]
<img width="338" alt="Capture d’écran 2019-12-12 à 16 06 43" src="https://user-images.githubusercontent.com/36261410/70723666-91657000-1cf9-11ea-8b97-a3beeea16bed.png">

**Comment by nedbaldessin** [comment]
Et bien il se trouve que c'était un bug de Chrome !
Fixé en tout cas.
