### ISSUE TITLE
Bouton télécharger

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#295]
Le bouton télécharger apparait apparait sur desktop. Le garder juste pour mobile et tablette comme version précédente.
<img width="995" alt="Capture d’écran 2019-12-16 à 10 26 47" src="https://user-images.githubusercontent.com/36261410/70895323-06cd8b00-1fef-11ea-815a-67f6a5281800.png">

**Comment by nedbaldessin** [comment]
Le problème initial soulevé en #209 est spécifique à iOS version 12 et inférieur. Il a été résolu en version 13. Le problème n'existe pas sous Android (testé dans Browser et Chrome), qui affiche un dialogue de confirmation de téléchargement.

Par conséquent, je suis revenu au comportement initial, en faisant l'impasse sur les iOS anciens.
