### ISSUE TITLE
Images | Il semble avoir encore des liens images manquants

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#309]
exemple dans cette sélection : 
https://collection.mobiliernational.culture.gouv.fr/selections/152

avec cet objet : https://collection.mobiliernational.culture.gouv.fr/objet/undefined

ou celui-ci (message d'erreur différent)
https://collection.mobiliernational.culture.gouv.fr/objet/undefined
ou
https://collection.mobiliernational.culture.gouv.fr/objet/undefined

**Comment by nedbaldessin** [comment]
Corrigé
