### ISSUE TITLE
Saut de ligne par défaut ne pas mettre d'espace avant

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#360]
Mettre un saut de ligne par défaut sans espace avant. Actuellement à chaque saut de ligne cela ajoute un espace avant : 
<img width="577" alt="Capture d’écran 2021-05-28 à 17 49 59" src="https://user-images.githubusercontent.com/36261410/120010262-3999f200-bfdd-11eb-9432-38650cb61ea2.png">

Mettre un comportement ordinaire

**Comment by nedbaldessin** [comment]
Oui, nous en avions discuté il y a bien longtemps : par défaut, le comportement des traitements de texte c'est un retour = un nouveau paragraphe, et un majuscule-retour = un retour à la ligne simple. Donc je laisse tel quel pour le moment.
