### ISSUE TITLE
Intégration gif et video ?

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#374]
cela ne fonctionne pas pour moi un chemin particulier à suivre @nedbaldessin ?
<img width="1279" alt="Capture d’écran 2022-06-23 à 16 51 16" src="https://user-images.githubusercontent.com/36261410/175328683-21f6deec-2ed0-49b1-b29e-06bd2200d6af.png">

**Comment by nedbaldessin** [comment]
Petit tuto, pour référence :)
Dans l'éditeur de blocs, choisir `Code (embed vidéo…)`. Aller sur YouTube, trouver sa vidéo, et clicker sur le bouton `Share`, et dans le dialogue modal, choisir `Embed`. Cliquer sur `Copy` pour copier le code d'embed. Enfin, coller le code d'embed dans le champ du backoffice.

<img width="986" alt="image" src="https://user-images.githubusercontent.com/69353/175919845-9626b3fc-c563-4314-bcc7-e97a0f1b337e.png">
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/69353/175920237-a95f122e-2047-40ea-957d-f800d69fb7db.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/69353/175920580-577c51d6-2485-4a24-ba1a-33e17dd8dace.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/69353/175920860-d2752800-2cc8-4dde-a9da-b270c6858450.png">
<img width="965" alt="image" src="https://user-images.githubusercontent.com/69353/175921084-618f4dd5-7532-4c9e-b0dc-56a05b81187a.png">
