### ISSUE TITLE
Le gris sur fond noir est #ACACAC pour respecter l'accessibilité. Sur fond blanc il reste ##7c7c7c

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#376]
Il doit rester #ACACAC sur fond noir mais
et #7c7C7C sur fond blanc

**Comment by nedbaldessin** [comment]
J'ai ajouté le support du texte gris dans l'éditeur de texte riche.
On ne peut pas varier en fonction de la couleur de fond.
J'ai conservé l'italique, pour sa qualité sémantique (demande d'Hélène).
