### ISSUE TITLE
Corriger marges

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#377]
- [ ] Margin-top de heading2 est de 150px non 200px
- [ ] Si il s'agit d'un enchainement fond noir/blanc, 150px sur chaque fond
- [x] Après les heading2, 80px margin-bottom
- [ ] Après les citations 80px
- [ ] Ajouter espace après fond noir (150px)
<img width="1274" alt="120010799-d8bee980-bfdd-11eb-8cc0-0e0bdd92e7e5" src="https://user-images.githubusercontent.com/36261410/130963081-3f9ae177-e3bd-4f0c-99f2-ebe380feb8c2.png">
- [ ] Ajouter espaces avant après de 80px pour les images pleines pages actuellement : 
<img width="1219" alt="120010426-6c43ea80-bfdd-11eb-9e23-9124da3b6f52" src="https://user-images.githubusercontent.com/36261410/130963302-e01a2f8f-ba89-4508-a633-925dc980c541.png">
<img width="1353" alt="120010438-70700800-bfdd-11eb-837b-3c4f912dcd83" src="https://user-images.githubusercontent.com/36261410/130963423-17c740c4-cd17-45ba-935a-be9b9ace6b30.png">
- mosaiques d'image : 30px avant le texte, 40px après (min) actuellement : 
<img width="987" alt="Capture d’écran 2021-08-26 à 14 35 25" src="https://user-images.githubusercontent.com/36261410/130963686-6bada44e-d239-424d-98cc-1fb5f67850e1.png">
- [ ] vérifier cet enchainement :
<img width="1455" alt="Capture d’écran 2021-08-26 à 14 56 18" src="https://user-images.githubusercontent.com/36261410/130966574-8f9ae708-8fa1-4699-991d-c3ba74cca4bc.png">
-[ ] 150px de marge dans le noir après chaque fin de sous-partie 
<img width="1078" alt="Capture d’écran 2021-08-26 à 15 07 48" src="https://user-images.githubusercontent.com/36261410/130968136-640bdd40-4185-4d3a-ab29-d7c656182299.png">

**Comment by nedbaldessin** [comment]
Certains points sont sous-spécifiés, donc je n'ai pas pu les reproduire.
Les autres sont corrigés.
