### ISSUE TITLE
Sous-titre à mettre en forme

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#378]
<img width="352" alt="Capture d’écran 2021-08-26 à 14 27 34" src="https://user-images.githubusercontent.com/36261410/130962591-e4413d7e-3eaf-4869-aaeb-7f223a6c1bf8.png">

**Comment by nedbaldessin** [comment]
Il faudrait ajouter un style dans l'éditeur wysiwyg, genre "h3".

**Comment by nedbaldessin** [comment]
On doit utiliser la balise H3 dans les grilles pour obtenir ce style de titre.

**Comment by lauriechap** [comment]
je ne vois pas comment l'appliquer ?

**Comment by nedbaldessin** [comment]
Il s'applique dans le bloc de type "Grille". Ce style n'est pas applicable ailleurs. 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/69353/177805457-1503de7c-2187-4998-960a-c00ae63b2626.png">
