### ISSUE TITLE
Pourrait-on limiter la hauteur des images pleine page, ou intégrer seulement des formats paysage ?

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#383]
Sinon il se passe cela :
<img width="717" alt="Capture d’écran 2021-08-26 à 15 01 18" src="https://user-images.githubusercontent.com/36261410/130967354-ab975344-a205-43aa-800e-885470f36774.png">

**Comment by nedbaldessin** [comment]
L'outil de crop est justement là pour traiter ce genre de situation.
