### ISSUE TITLE
Résoudre mise en page définition

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#384]
<img width="978" alt="Capture d’écran 2021-08-26 à 15 03 46" src="https://user-images.githubusercontent.com/36261410/130967582-4aae8de4-97f2-4ef1-98dc-088511d1599b.png">
Permettre de les intégrer sur deux colonnes et garder un fond uni blanc ou noir.

màj 6.07.22
il n'y a plus les espaces blancs, mais les paragraphes de définition sont trop longs, garder la taille style dans lequel il est intégré
<img width="1244" alt="Capture d’écran 2022-07-06 à 17 43 41" src="https://user-images.githubusercontent.com/36261410/177590886-56b48c15-79c8-423d-8422-c0fe104b5bc1.png">

**Comment by nedbaldessin** [comment]
Voir #386

**Comment by nedbaldessin** [comment]
L'espacement entre blocs sur fond noir est résolu.
Pour l'intégration dans le block Texte + Images (sur 2 colonnes), il faut utiliser le style gras et italique dans le texte.
