### ISSUE TITLE
Permettre les exposants dans les titres et intertitres

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#389]

**Comment by nedbaldessin** [comment]
Pas possible techniquement dans l'état des choses (parce que gestion des slugs à partir des titres, etc).

En revanche, on peut utiliser la palette Unicode du système pour saisir des caractères "exposant" (superscript) : https://unicode-table.com/en/sets/superscript-and-subscript-letters/
