### ISSUE TITLE
développer téléchargement

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#41]
**Description du défaut**
Au clic sur téléchargement celui-ci ne se lance pas, et n'intègre pas les détails des photographes on a par défaut ici toujours Isabelle bideau

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur un objet
3. Cliquer sur télécharger
4. Voir l'erreur

**Comportement attendu**
Au clic sur téléchargement, celui-ci se lance automatiquement et le nom du photographe est intégré dans le message d'info qui apparait

**Comment by lauriechap** [comment]
Au clic en dehors du message (rectangle vert), revenir à la page précédente

**Comment by nedbaldessin** [comment]
Fait.
