### ISSUE TITLE
Ajout halo couleur

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#418]
**Description du défaut**
- [ ] Ajouter Halo comme sur maquette
- bleu au dessus de la ligne de flottaison
- vieux rose à droite sous premier article
- bleu sur "artisans..."
- doré dans la section "nos ateliers" près de "tout voir"
- vieux rose "nos histoires d'objet"
- bleu à droite de "nos créateurs
- fushia + bleu sur la dernière image

Sur les articles 

- [ ] enlever les espaces transparents blancs dessus les images
<img width="718" alt="Capture d’écran 2022-04-27 à 15 51 54" src="https://user-images.githubusercontent.com/36261410/165534595-001a1ae6-c630-4dc6-9411-68c609003eb7.png">

**Comment by lauriechap** [comment]
<img width="192" alt="Capture d’écran 2022-04-27 à 14 54 34" src="https://user-images.githubusercontent.com/36261410/165522606-42f3c68d-ca07-4d0e-9cd0-33aa35d563ae.png">

**Comment by nedbaldessin** [comment]
Pour info, ces halos m'ont donné beaucoup de fil là retordre, en raison du compositing entre les blocs et les fonds. J'ai du simplifier légèrement quelques dégradés, pour rendre la chose possible.
