### ISSUE TITLE
Créer aperçu des sections par page

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#426]
Cf maquettes

**Comment by nedbaldessin** [comment]
Tu confirme que tu parles bien de ceci ?
<img width="232" alt="image" src="https://user-images.githubusercontent.com/69353/165543685-3beb2f83-52e3-43bc-9e40-a43d3c5a53ca.png">

**Comment by lauriechap** [comment]
yes !
