### ISSUE TITLE
Supprimer catégories vides "biblio" et "crédits"

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#427]
Si non renseignées, supprimer les rubriques biblio et crédits
<img width="1767" alt="Capture d’écran 2022-04-27 à 15 54 53" src="https://user-images.githubusercontent.com/36261410/165535214-394f626b-352d-48c8-b0a1-e5ce3dd06d80.png">

**Comment by nedbaldessin** [comment]
Fixed & deployed.
