### ISSUE TITLE
classification époque de création

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#43]
**Description du défaut**
à l'utilisation du filtre "année de création", les objets ne sont pas rangés dans la bonne tranche d'années, et sont quelques fois sur 3 périodes différentes

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com'
2. Cliquer sur 'année de création'
3. Cliquer sur 'napoléon III' ou 'Restauration'
4. Cliquer sur les objets
5. Voir l'erreur

**Comportement attendu**
Au clic sur Napoléon III seulement les objets construits pendant cette période sortent
Si un objet à la donnée "époque restauration" ou "époque louis-philippe" l'objet apparaitra seulement dans la catégorie mentionné dans sa fiche objet

On trouve ce problème par exemple avec les objets GME-12301-000 et GME-11940-000

**Comment by lauriechap** [comment]
Aussi changer l'intitulé du filtre 'année de création' en 'période de création'
+ rendre cliquable les dates et pas seulement les ronds pour pouvoir choisir une période de date

**Comment by lauriechap** [comment]
À la sélection d'une période mettre les filets blancs qui encadrent la période. Cf capture
<img width="1152" alt="annee 2 2 1" src="https://user-images.githubusercontent.com/36261410/49226829-efbdfa00-f3e7-11e8-8a42-716ed71bd263.png">

**Comment by nedbaldessin** [comment]
Nota bene : Il faut modifier les époques pour utiliser des dates (année-mois-jour) plutôt qu'une année seule, pour éviter le problème de superposition d'intervales. Prévoir un seed.

**Comment by nedbaldessin** [comment]
Résolu en évitant les superpositions d'années (strictement supérieur à, ou strictement inférieur à…).
