### ISSUE TITLE
intégrer la grille d'objet des collections

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#431]
actuellement : 
<img width="1598" alt="Capture d’écran 2022-04-27 à 16 01 24" src="https://user-images.githubusercontent.com/36261410/165536442-48406f12-5875-4836-be04-f1a73e17de21.png">

**Comment by nedbaldessin** [comment]
Problème lié à un problème de chargement des images de la collection, maintenant résolu sur staging.
