### ISSUE TITLE
Mise en forme tablette

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#432]
- [ ] intro
<img width="384" alt="Capture d’écran 2022-04-27 à 16 16 27" src="https://user-images.githubusercontent.com/36261410/165539360-177f893f-58e4-4a01-9405-d00987e83303.png">

- [ ] margin right et left pour l'ensemble du texte dans le corps 
actuellement : 
<img width="652" alt="Capture d’écran 2022-04-27 à 16 17 35" src="https://user-images.githubusercontent.com/36261410/165539624-cc7b5b6f-01c7-4c60-992b-292f6cc7f825.png">

- [ ] corriger espaces avant légende + avant titre de section
<img width="740" alt="Capture d’écran 2022-04-27 à 16 18 07" src="https://user-images.githubusercontent.com/36261410/165539787-23f46a9a-d76d-4f0e-9095-45218faad0de.png">
<img width="713" alt="Capture d’écran 2022-04-27 à 16 18 45" src="https://user-images.githubusercontent.com/36261410/165539862-ad6638bd-2576-42c8-9e45-00d4f789cf83.png">

- [ ] pb "mise en exergue" sortant de l'écran à droite
<img width="497" alt="Capture d’écran 2022-04-27 à 16 20 40" src="https://user-images.githubusercontent.com/36261410/165540357-dc62e761-42d6-4389-baaa-c6bd6c4acc53.png">

**Comment by nedbaldessin** [comment]
Je vais fermer ce ticket, parce que je pense avoir résolu les problèmes soulevés.
Je me demande si tous les espaces verticaux sont bons… je referais une passe quand j'aurais terminé le reste.
