### ISSUE TITLE
supprimer les rubriques non utilisées

### ISSUE THREAD

**Issue by aguirregabiria** [entrepreneur-interet-general/gobelins#434]
Aller sur "rubriques" https://admin.beta.collections-mobilier-national.com/encyclopedie/sections
sélectionner une rubrique
cliquer sur "actions groupées"
la liste déroulante semble vide

On veut pouvoir supprimer la rubrique "Ameublement"

**Comment by nedbaldessin** [comment]
Vu en réunion
