### ISSUE TITLE
Mise en avant de 2 articles au lieu de 3

### ISSUE THREAD

**Issue by aguirregabiria** [entrepreneur-interet-general/gobelins#435]
j'ai choisi 2 articles mis en avant pour https://admin.beta.collections-mobilier-national.com/encyclopedie/articles/71/edit, mais j'ai l'impression que ça ne marche pas (je ne les vois pas en preview). Le 3ème article est choisi aléatoirement ? 
Ou bien en mode manuel il faut forcément en choisir 3 ?

**Comment by nedbaldessin** [comment]
Ok, ce module n'était pas terminé, c'est maintenant fait.
Si on spécifie un, deux, ou trois (c'est le max) articles "mis en avant", alors on affiche ceux-là.
Sinon, on affiche trois articles de la même rubrique.
