### ISSUE TITLE
[home] modifier le titre Découvrez nos...

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#445]
Pour s'accorder avec les nouvelles rubriques : 
- découvrez nos métiers, techniques, histoires d'objet ou créateur
- mettre les rubriques dans le même ordre dans la page, soit faire remonter la rubrique "technique"

@nedbaldessin 
il manque juste de tout mettre au pluriel pour plus de cohérence dans les rubriques et sur le menu pour passer le ticket en terminé

**Comment by nedbaldessin** [comment]
OK, j'ai passé 2 rubriques au pluriel :
Métier => Métiers
Créateur => Créateurs

En fait, on peut administrer cela dans le back office ici
https://admin.beta.collections-mobilier-national.com/encyclopedie/sections

Le menu de navigation utilise les rubriques du backoffice, donc il reste à jour.
