### ISSUE TITLE
[home] au clic sur l'image d'un article cela renvoit à l'article

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#447]
actuellement il y a juste le hover

**Comment by nedbaldessin** [comment]
Tu peux m'en dire plus, parce que je n'arrive pas à reproduire. Pour moi ça fonctionne bien.

**Comment by lauriechap** [comment]
sur chrome, mac, si je clique sur l'image d'un aperçu d'article sur la home rien ne se passe, il faut que je clique sur le titre pour avoir accès à l'article.
