### ISSUE TITLE
[home] + [recirculation] appliquer les hovers maquettés

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#448]
<img width="853" alt="Capture d’écran 2022-06-23 à 13 53 32" src="https://user-images.githubusercontent.com/36261410/175292732-888e29a9-2420-4382-a2a0-687f74cffedc.png">

**Comment by nedbaldessin** [comment]
Ha, effectivement je n'avais pas le bon fichier Figma !
