### ISSUE TITLE
[article] Problème de bande blanche sur fond noir non résolu

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#451]
<img width="1667" alt="Capture d’écran 2022-06-23 à 14 00 36" src="https://user-images.githubusercontent.com/36261410/175294648-953798e3-eb91-4646-a4a2-29d2e312bcad.png">
 exemple : https://beta.collections-mobilier-national.com/encyclopedie/lecole-des-gobelins

Toujours pas résolu exemple @nedbaldessin : https://beta.collections-mobilier-national.com/encyclopedie/les-alienes-du-mobilier-national

**Comment by nedbaldessin** [comment]
Ok, le problème semble être enfin résolu. Il concernait les images pleine largeur.
