### ISSUE TITLE
erreur superposition halo

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#457]
https://beta.collections-mobilier-national.com/encyclopedie/le-fil-dor-en-tapisserie

<img width="915" alt="Capture d’écran 2022-06-23 à 17 03 43" src="https://user-images.githubusercontent.com/36261410/175331246-9b9d939b-c624-4a79-9c4b-c5de29d3fa06.png">

màj 6.7.22
cf ticket#472

**Comment by nedbaldessin** [comment]
Fixed in [764ab95]
