### ISSUE TITLE
recherche libre - scroll to top

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#46]
**Description du défaut**
Lors d'une nouvelle recherche libre, la page résultats reste auniveau du précédent scroll, il faut donc remonter la page pour voir les premiers résultats

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Scroller dans les résultats aléatoires
2. Cliquer sur rechercher, effectuer une recherche
4. Voir l'erreur

**Comportement attendu**
Lors d'une nouvelle recherche, on accède directement aux premiers résultats qui sont les plus pertinents

**Comment by nedbaldessin** [comment]
Il faut systématiquement réinitialiser la position de scroll quand on charge de nouveaux résultats.
