### ISSUE TITLE
Dans la rubrique nouveaux articles, faire apparaitre les nouveaux articles

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#462]
<img width="1724" alt="Capture d’écran 2022-06-27 à 10 26 43" src="https://user-images.githubusercontent.com/36261410/175894940-b95fe091-9817-4b70-88a2-eb778175b33a.png">
Actuellement cela ne semble pas être les nouveaux articles qui apparaissent dans la rubrique

**Comment by nedbaldessin** [comment]
J'ai mis en place une éditorialisation (mise-en-avant manuelle) de ces 6 items, je me disais que ce serait plus flexible pour l'équipe de rédaction, si la fréquence de publication est irrégulière, ou si ils ont des articles moins importants (qui sont récents, mais qui ne méritent pas une mise en avant) :
https://admin.beta.collections-mobilier-national.com/featured/homepage

**Comment by nedbaldessin** [comment]
Donc après discussion en réunion, changement du comportement : on liste 4 pages de 9 items, en ordre ante-chronologique. 
https://beta.collections-mobilier-national.com/encyclopedie/recent
