### ISSUE TITLE
Recette menu

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#469]
MOBILE

- [x] permettre le scroll dans le menu (derniers items non accessibles sur petits écrans actuellement)
- [x] En dessous des titres "collection" ""encyclo.." "l'institution" mettre seulement 20 px d'espace 

- [ ] au clic sur métier, création... dans le menu renvoyer aux ancres dans la home pas aux résultats de recherche
- [x] line height des textes "métier, histoire d'objet.." passer de 100% à 120%

**Comment by nedbaldessin** [comment]
Je ferme le ticket, après avoir discuté avec Laurie pour le point n°3.
