### ISSUE TITLE
Recette recherche

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#471]
MOBILE 

- [x] Centrer la loupe dans le bouton sur la home 
actuellement sur ios :
![IMG_3126](https://user-images.githubusercontent.com/36261410/177551109-bec49435-dde5-44b4-8f6c-f86f4e864e2c.PNG) (même problème sur ipad)

- [x] reduire line-height à 140%  sur X articles trouvés....

- [ ] non apparition des images sur ipad
![IMG_0225](https://user-images.githubusercontent.com/36261410/177555031-22a83462-bb8b-4d56-acf9-7eb672f58fd6.PNG)

GLOBAL

- [x] aligner texte thèmes et textile, bois etc

- [x] mettre en forme "vous ne trouvez pas le sujet qui vous..." à la même taille de typo que "aucun article..."

**Comment by nedbaldessin** [comment]
Je n'ai pas pu reproduire les images non-affichées. Le reste est OK.
