### ISSUE TITLE
Filtre matière : exceptions pour catégories [Techniques de tissage], et [Cuir]

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#49]
**Description du défaut**
Dans textile intégrer la sous catégorie "technique de tissage"

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur 'matière'
3. Aller dans textile
4. Voir la modification

**Comportement attendu**
Dans textile appliquer la classification détaillée ici : https://docs.google.com/document/d/1FYZoZtv5B5jpQpv3IqpPuRS25ToSk2M7L2ek93J1fTU/edit#heading=h.nn669ek2w188

**Comment by lauriechap** [comment]
**Description du défaut**
Intégrer une exception, sur la fiche objet pour les objets de la catégorie "cuir et skaï" indiquer seulment la sous catégorie "cuir" ou "skaï" ou "daim"…

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection?q=starck&page=1'
2. Lire la catégorie matière
3. Voir l'incohérence

**Comportement attendu**
Avoir seulement "skaï" ou "cuir" ou "daim" pas suivi par "cuir et skaÏ"

<img width="1586" alt="capture d ecran 2018-11-30 a 11 11 37" src="https://user-images.githubusercontent.com/36261410/49282976-c907ce00-f490-11e8-95fb-10737d53fba3.png">

**Comment by nedbaldessin** [comment]
Fait.
