### ISSUE TITLE
Voir "tous" les objets d'un même type

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#5]
**Description du défaut**
Remplacer "voir seulement" par "tous" dans type d'objet 3e panneau

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Cliquer sur '.type d'objet'
3. Survoler 'chaise'
4. Voir l'erreur

**Comportement attendu**
Possibilité de cliquer sur tous, afin de voir tous les types de chaises, tous les types de tables…

**Comment by nedbaldessin** [comment]
L'UX des filtres hiérarchiques a été revu et corrigé dans la branche "ux-change-types".
