### ISSUE TITLE
recherche libre

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#51]
**Description du défaut**

Les objets sans photos tombent avant les objets ayant les même données mais avec photo.

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Rechercher "polynésie"
3. Voir l'erreur

**Comportement attendu**
Voir d'abord les objets les plus pertinents avec photos puis ceux sans photos.

<img width="1324" alt="capture d ecran 2018-11-30 a 16 14 19" src="https://user-images.githubusercontent.com/36261410/49297652-9d4e0d80-f4bb-11e8-948d-582a3437504a.png">

**Comment by nedbaldessin** [comment]
Résolu par a41cc48.
J'ai modifié le critère d'ordre pour que le critère de présence et de qualité des images soit un **facteur** du score de pertinence, et non plus un score de pertinence **secondaire**.

**Comment by lauriechap** [comment]
@nedbaldessin cela ne résout pas le pb, as-tu une idée de pourquoi ?
