### ISSUE TITLE
recherche libre avec pronom

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#52]
**Description du défaut**
Une description claire et concise du problème.

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Rechercher sur 'de gaulle'
3. Voir l'erreur

**Comportement attendu**
Seulement les résultats avec "de gaulle" dans leur fiche devraient apparaître

<img width="1427" alt="capture d ecran 2018-11-30 a 15 47 50" src="https://user-images.githubusercontent.com/36261410/49296121-b228a200-f4b7-11e8-918a-9bdeaf22e968.png">

**Comment by nedbaldessin** [comment]
Résolu avec a41cc48.

Pour l'analyse des nom d'auteurs (prénoms et noms), j'ai ajouté une liste de pronoms à ignorer (stopwords) : `de`, `le`, `et`, `da`, `l’`, `d’`.
