### ISSUE TITLE
recherche libre date

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#54]
**Description du défaut**
À la recherche d'une date cela ne fonctionne pas le nombre est noyé dans les autres nombres de la fiche objet

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Rechercher 1980
4. Voir l'erreur

**Comportement attendu**
Avoir les objets créer en 1980 en priorité

**Comment by nedbaldessin** [comment]
J'ai boosté l'année de conception, et on a bien le résultat voulu.
