### ISSUE TITLE
recherche numéro d'inventaire

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#55]
**Description du défaut**
À la recherche d'un numéro d'inventaire on a une multitude d'objets qui n'ont pas ce numéro
**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection'
2. Rechercher 'GML-11361-000'
3. Voir l'erreur

**Comportement attendu**
Tomber seulement sur l'objet avec ce numéro d'inventaire ou sa série

<img width="1444" alt="capture d ecran 2018-12-05 a 14 26 24" src="https://user-images.githubusercontent.com/36261410/49516427-dc080d00-f899-11e8-87f9-8663823fac81.png">

**Comment by nedbaldessin** [comment]
Implemented in 2eab2c6
