### ISSUE TITLE
État hover / select des filtres

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#70]
**Description du défaut**
L'état hover / select des filtres actuels fait sauter les contenus à cause du changement de graisse

**Comportement attendu**
Utiliser les nouvelles maquettes, figma > corection UX > hover/select

HOVER
<img width="1152" alt="1bis" src="https://user-images.githubusercontent.com/36261410/49932807-4805f900-feca-11e8-8769-1d2bb49fc789.png">

SELECT
<img width="1152" alt="1bis 2" src="https://user-images.githubusercontent.com/36261410/49873981-85607d00-fe1d-11e8-945a-5e8f511f2eb3.png">

**Comment by nedbaldessin** [comment]
Fait.
