### ISSUE TITLE
Ajout bouton supprimer tous les critères + changement hover

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#72]
**Description du défaut**
1. Pour des recherches complexes supprimer chaque critère prend trop de temps pour l'utilisateur
2. mauvaise compréhension de l'état hover pour la suppression des critères

**Comportement attendu**
Voir maquettes figma > correction UX > suppression critère
Au clic sur le bouton à la fin de la phrase des critères de recherche > suppression de l'ensemble des critères (recherche réinitialiser)

<img width="1152" alt="accueil 12" src="https://user-images.githubusercontent.com/36261410/49887990-22331280-fe3e-11e8-9f63-5ddd34c7d1d6.png">

<img width="1152" alt="accueil 13" src="https://user-images.githubusercontent.com/36261410/49888079-5575a180-fe3e-11e8-89b2-49ccc614fa8b.png">

**Comment by nedbaldessin** [comment]
@lauriechap C'est en ligne sur staging. Pour l'instant j'ai gardé le "barré" précédant pour aller vite, mais dis-moi si tu tiens au barré en couleur.

**Comment by lauriechap** [comment]
@nedbaldessin on peut laisser comme ça pour l'instant, il faut cependant améliorer le hover du bouton qui est aléatoire. Seulement certaines zones du bouton sont cliquables.

**Comment by nedbaldessin** [comment]
Corrigé avec #104
