### ISSUE TITLE
fiche objet avec une seule image

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#83]
**Description du défaut**
Actuellement lorsqu'un objet a une seule image sur la fiche détail, sa miniature s'affiche tout de même. Les utilisateurs tentent donc de cliquer sur celle-ci pensant qu'il s'agit d'une autre photo de l'objet.

**Processus pour le constater**
Les étapes pour reproduire le comportement défectueux :
1. Aller sur la page 'http://beta.collections-mobilier-national.com/collection?page=1'
2. Voir le problème

**Comportement attendu**
Si un objet a une seule image, appliquer les maquettes ci-dessous
figma > correction UX > fiche objet / une image

<img width="1152" alt="photo-verticale" src="https://user-images.githubusercontent.com/36261410/50090656-8e7c9000-0209-11e9-9fc0-dbd97870a957.png">

![clic retour](https://user-images.githubusercontent.com/36261410/50090685-a05e3300-0209-11e9-89dd-3ed1fc9c8c16.png)
<img width="1152" alt="zoom" src="https://user-images.githubusercontent.com/36261410/50090699-a7854100-0209-11e9-9e10-1cf6b0be398c.png">

**Comment by nedbaldessin** [comment]
Ce problème a été corrigé il y a bien longtemps, je ne sais plus exactement.
Bisous.
