### ISSUE TITLE
intégration des crédits et mentions légales

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#88]
Simplification des maquettes  : figma > corrections UX > crédits et mentions légales
///ATTENTION/// attente des dernières corrections du SG pour le texte
<img width="1152" alt="credit" src="https://user-images.githubusercontent.com/36261410/50340421-313f5200-051b-11e9-9242-155d2818383e.png">

**Comment by nedbaldessin** [comment]
Fait.
