### ISSUE TITLE
Ajout de style

### ISSUE THREAD

**Issue by lauriechap** [entrepreneur-interet-general/gobelins#93]
**Description du défaut**
Ajouter les styles  Gothique, Renaissance, Art Nouveau
Chronologiquement : 
Gothique Renaissance Louis XIII Louis XIV Régence Louis XV Transition Louis XVI Directoire Empire Restauration Louis-Philippe Napoléon III Art Déco Art Nouveau Années 1940 Années 1950 Années 1960 Années 1970 Années 1980 Années 1990 Années 2000 Années 2010 Étranger

**Comment by nedbaldessin** [comment]
Ok, je lance un nouvel import sur staging.
J'ai corrigé l'ordre chrono : l'art nouveau vient avant l'art déco :)

**Comment by lauriechap** [comment]
Bien vu, merci !

**Comment by lauriechap** [comment]
@nedbaldessin H.C m'informe que le style "Transition" va être supprimer. Voici donc la dernière version :
Gothique Renaissance Louis XIII Louis XIV Régence Louis XV  Louis XVI Directoire Empire Restauration Louis-Philippe Napoléon III Art Nouveau Art Déco  Années 1940 Années 1950 Années 1960 Années 1970 Années 1980 Années 1990 Années 2000 Années 2010 Étranger

**Comment by nedbaldessin** [comment]
C'est un problème de nettoyage de données : lors du prochain export SCOM, quand il n'y aura plus d'objets classés dans `Transition`, alors ce style ne sera plus affiché.
